version: '3.9'

services:
  cassandra:
    image: cassandra:4.1.0
    ports:
      - 9042:9042
    volumes:
      - ~/apps/cassandra:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=cloudinfra